# Generated by Django 4.1.3 on 2022-12-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_food_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200, verbose_name='판매할 재능'),
        ),
    ]
